### ISSUE TITLE
Are you really meant to be a public repository?

### ISSUE THREAD

**Issue by oliverlockwood** [sky-uk/css#13]
We have noticed this repository is marked as public.  There are certain standards required before a repository in the `sky-uk` org can be made public, including the presence of valid `LICENSE.md`, `README.md`, and `CONTRIBUTING.md` files.
Unless there is good reason to make a repository public, we create as private by default, since we only want to publicly expose repositories that are of a high standard, in order to project a positive profile to the wider development community.
-  Repos without license information are immediately made private.
-  Repos failing the other criteria will be made private after 30 days.

Please resolve these problems ASAP and close this GitHub issue when you have done so.

If you have any questions, please ask them on the [#github](https://sky.slack.com/archives/github) Slack channel.

**Comment by joebell93** [comment]
Resolved
